# Window
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Colors
RED = 0
GREEN = 1
BLUE = 2

# Paddle
PADDLE_LEFT = 0
PADDLE_RIGHT = 1
PADDLE_WIDTH = 90
PADDLE_HEIGHT = 7

# Brick
BRICK_WIDTH = WINDOW_WIDTH // 13
BRICK_HEIGHT = (WINDOW_HEIGHT // 5) // 4

# Grid
GRID_WIDTH = WINDOW_WIDTH // BRICK_WIDTH
GRID_HEIGHT = (WINDOW_HEIGHT // 3) // BRICK_HEIGHT
GRID_REMAINDER_WIDTH = (WINDOW_WIDTH % BRICK_WIDTH)

# angles
ANGLE_DELTA = 150
BASE_ANGLE = 360 - ANGLE_DELTA/2
