
FPS = 60

# Window
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Colors
RED = 0
GREEN = 1
BLUE = 2

# Paddle
PADDLE_LEFT = 0
PADDLE_RIGHT = 1
PADDLE_WIDTH = 60
PADDLE_HEIGHT = 20

# Brick
BRICK_WIDTH = 60
BRICK_HEIGHT = 30

# Grid
GRID_WIDTH = WINDOW_WIDTH // BRICK_WIDTH
GRID_HEIGHT = (WINDOW_HEIGHT // 3) // BRICK_HEIGHT
GRID_REMAINDER_WIDTH = (WINDOW_WIDTH % BRICK_WIDTH) - GRID_WIDTH
